CREATE TABLE IF NOT EXISTS system_installation (
  installation_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  setup_state ENUM('UNCONFIGURED','SERVER_CONFIG_IN_PROGRESS',
    'INFRA_READY_APP_SETUP_PENDING','APP_SETUP_IN_PROGRESS',
    'INITIALIZED','MAINTENANCE','SETUP_LOCKED') NOT NULL DEFAULT 'UNCONFIGURED',
  server_version VARCHAR(20),
  installed_at TIMESTAMP NULL,
  initialized_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO system_installation (setup_state, server_version) VALUES ('UNCONFIGURED', '1.0.0');
